### ISSUE TITLE
Harvest runs non-Django apps

### ISSUE THREAD

**Issue by danni** [koterpillar/aloe_django#13]
Running `./manage.py harvest` also causes non-Django apps to be run.

**Comment by koterpillar** [comment]
Ack. The current behaviour is inherited from `aloe` which knows nothing about applications.

**Comment by danni** [comment]
Is that wrong?

**Comment by koterpillar** [comment]
The behaviour here should mirror ./manage.py test,  aloe itself might need to be changed for that but it obviously won't depend on Django itself.

**Comment by koterpillar** [comment]
Just checked, Nose (via `manage.py test`) runs tests from unrelated packages too. Looked through their issues, but couldn't find anything obvious that suggests that's unexpected; neither does the runner code.

**Comment by koterpillar** [comment]
Even without Nose, Django's `manage.py test` ignores apps, I don't see why should Aloe be different.
