### ISSUE TITLE
ERROR - manage.py harvest in django 1.8

### ISSUE THREAD

**Issue by cyber778** [koterpillar/aloe_django#34]
After I installed django 1.8 and run the harvest command in shell I get this:

``` python
ERROR: Failure: WebDriverException (Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.
)

```

usually what happens was that the test ran perfect now it just makes the FF browser comeup but nothing happens.

*using FF v.43

**Comment by koterpillar** [comment]
How is this a bug in Aloe Django? It looks like you need to update `selenium` due to updated Firefox.

**Comment by cyber778** [comment]
I guess you are right it probably isn't an aloe django problem,
I did that update it doesn't help, that's also the answers I've seen around.
I will post this issue there.

**Comment by koterpillar** [comment]
Also please check error log as it says.

**Comment by nikolas** [comment]
Firefox 43+ requires selenium version 2.48.0.

**Comment by cyber778** [comment]
2.48.0 fixed the issue, sorry about the false alarm, Thanks for the fast reply!
