### ISSUE TITLE
ImportError: No module named features

### ISSUE THREAD

**Issue by nikolas** [koterpillar/aloe_django#35]
Hi, I have a project layout like this:

``` bash
~/src/project $ ls features/
__init__.py  terrain.py
~/src/project $ ls project/main/features/
homepage.delete.feature  login.feature   manage_publish_options.feature
homepage.feature         main-steps.py   manage_selection_visibility.feature
instructor.feature  __init__.py  manage_sources.feature
```

I can't figure out how to run my tests, which I'm converting over from lettuce. Here's the error I get:
http://dpaste.com/1ND3PN6

**Comment by koterpillar** [comment]
Two suggestions:
- Do individual features work, e.g. `./manage.py harvest mediathread/main/features/login.feature`?
- Do `project` and `project/main` have an `__init__.py`?

**Comment by nikolas** [comment]
- `./manage.py harvest mediathread/main/features/login.feature` yields the same error

```
$ ls mediathread/__init__.py
mediathread/__init__.py
$ ls mediathread/main/__init__.py
mediathread/main/__init__.py
```

**Comment by nikolas** [comment]
It turns out that not _all_ of my features directories had an `__init__.py` file. I had some other app/features directories which aloe was trying and failing to load. Now I'm getting some other problems but they are separate and likely related to my application.
