### ISSUE TITLE
Is django_nose.NoseTestSuiteRunner required?

### ISSUE THREAD

**Issue by nikolas** [koterpillar/aloe_django#36]
Hi,
My Django project uses django's DiscoverRunner -- I have this set in `settings.py`:

``` python
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
```

The aloe-django documentation is telling me to set `TEST_RUNNER` to `django_nose.NoseTestSuiteRunner`:
https://aloe.readthedocs.org/projects/aloe-django/en/latest/#using-aloe-with-django

I would like to keep using the DiscoverRunner for all my django unit testing code, and only use the Nose runner with aloe. I think the documentation should include some clarification here, explaining how to do that, since some users won't want to switch their test runner to Nose if everything's set up for the DiscoverRunner.

**Comment by koterpillar** [comment]
Agreed, I'll do some testing to clarify the situation and change the documentation.

**Comment by koterpillar** [comment]
Changing `TEST_RUNNER` is not needed; in fact, the minimal setup can be seen from https://github.com/koterpillar/aloe_django/blob/master/tests/integration/test_stock_app.py. I've changed the documentation not to suggest enabling `django_nose`, is it clear now?

**Comment by nikolas** [comment]
Yeah, looks good.
