### ISSUE TITLE
using pdb with ./manage.py harvest

### ISSUE THREAD

**Issue by nikolas** [koterpillar/aloe_django#37]
I've been trying to debug issue #35, putting a pdb.set_trace() call in the find_and_load_step_definitions function of aloe/fs.py. When I've triggered the breakpoint, the pdb terminal doesn't open up.

Then I remembered since this is a django command, maybe I have to add something like `--pdb` in order for this to work, but that's for debugging the application tests, not the test framework itself.

In nose (which it looks like is what aloe is using to run these tests), it's documented that adding the `--pdb` option automatically opens the pdb prompt
http://nose.readthedocs.org/en/latest/plugins/debug.html, but because of what I mentioned, this isn't working either.

So, how do you use pdb when debugging something in aloe / aloe_django?

**Comment by koterpillar** [comment]
Did you add `-s` to disable Nose capturing the output? I have no problems using Pdb during harvest.

**Comment by nikolas** [comment]
Thanks! I added `-s` and it works. I should've read the harvest help.
