### ISSUE TITLE
Loading an sqlite database for aloe tests (lettuce migration)

### ISSUE THREAD

**Issue by nikolas** [koterpillar/aloe_django#39]
So, I know it's better to use factories instead of fixtures, but I have an application that loads an sqlite database called `lettuce.db` when the tests start. This application was set up to use lettuce.

I've finally got my tests working in aloe, now I just have to load this database so the tests can log in to the pre-determined user accounts. To give you an idea, here's how it's set up for lettuce in `terrain.py`:

``` py
@before.each_scenario
def reset_database(variables):
    world.using_selenium = False

    try:
        os.remove('lettuce.db')
        time.sleep(1)
    except OSError, e:
        if e.errno != errno.ENOENT:  # errno.ENOENT = no such file or directory
            raise  # re-raise exception if a different error occurred
        else:
            pass  # database doesn't exist yet. that's okay.

    os.system('cp scripts/lettuce_base.db lettuce.db')
```

How would you migrate this to aloe_django?

**Comment by koterpillar** [comment]
This is definitely not something I would endorse (do you store `lettuce_base.db` in version control? How are the changes to it reviewed?). However, if you really want to do this, set `GHERKIN_TEST_RUNNER` to your own class and override `setup_test_environment` in it.

**Comment by nikolas** [comment]
Thanks, this is turning out to be very tricky. My test database seems to be postgresql not sqlite. I'm just going to convert everything to more flexible factories. The lettuce_base.db file is in version control, I'm not sure how changes are reviewed.. I'm kind of new to this project.
